### ISSUE TITLE
Maintain or remove "force SSL" functionality

### ISSUE THREAD

**Issue by nbibler** [tylerhunt/rack-canonical-host#26]
This is related to #21: I didn't even realize it was a suggested function of this library to use it to ensure HTTPS usage.  That is much better provided by [rack-ssl](http://rubygems.org/gems/rack-ssl) which forces HTTPS usage, has proxy header support, secures cookies, adds HSTS headers, etc.

Seemingly, the scope of this middleware is to ensure that the host being requested is the singular, current canonical host to provide the response.  Venturing outside of checking and enforcing the requested Host (which can actually be quite tricky if you're going to account for proxy headers) feels like a slippery slope to me.

Should rack-canonical-host continue offering HTTP to HTTPS request conversion, or should that be the responsibility of the web server or of some other middleware?

**Comment by brian-kephart** [comment]
I know this is a long-closed issue, but I'm curious to know if there's a way of doing this that avoids multiple redirects. Right now, one middleware redirects to upgrade the protocol, while another redirects to the canonical domain. Is there a way of combining these two redirects without reversing this change?

**Comment by nbibler** [comment]
@brian-kephart: I believe you can pass a `host` option to `rack-ssl` and it'll use that over the requested host. See https://github.com/josh/rack-ssl/blob/master/lib/rack/ssl.rb#L20.

**Comment by brian-kephart** [comment]
Thanks for the response. I figured this out, but it took awhile. I had to:

1. Insert this middleware after ActionDispatch::SSL using the method in #36.
2. Configure SSL options in config/initializers/new_framework_defaults.rb to add `redirect: { host: ENV["CANONICAL_HOST"] }` to the hash.

This appears to have taken care of the multiple redirect issue.

**Comment by erikdahlstrand** [comment]
Just to fill in... sometimes you want multiple redirections (first upgrade the protocol, then redirect to the canonical domain). If you want to include your domain in the [HSTS preload list](https://hstspreload.org) it's a requirement. I wrote a couple of lines about it [here](https://github.com/tylerhunt/rack-canonical-host/issues/36#issuecomment-330813507).
