### ISSUE TITLE
301 Redirect issue

### ISSUE THREAD

**Issue by StevenHarlow** [tylerhunt/rack-canonical-host#31]
I have an issue where I switched to have a wordpress marketing application (hosted on a different server) take the place of the original www application.  Because any redirects were routed with a 301, it permanently stored in the browser.  Now when using a separate sub-domain for the main application (app.domain), we are having issues getting them to point to the correct domains for people who have already visited the site (they need to clear all cookies, but we'd like to not have to tell users to clear all cookies to see our site).  Do you know a way to correct this?  Also, perhaps consider redirecting with another status?

**Comment by tylerhunt** [comment]
Once the redirect is cached by the browser, I'm not sure there's much you can do about it. If you need something that provides another redirect status, you could take a look at using another middleware like [rack-rewrite](https://github.com/jtrupiano/rack-rewrite). Supporting that in `rack-canonical-host` is beyond its scope.
