### ISSUE TITLE
1.0 release?

### ISSUE THREAD

**Issue by nbibler** [tylerhunt/rack-canonical-host#34]
On the whole, this library seems to be pretty stable. Think it's time to call it a 1.0?

**Comment by dijonkitchen** [comment]
I think you can close this issue @nbibler. I think the repo uses [semantic versioning](http://semver.org/), so the 0 major version just means there aren't any breaking changes.

**Comment by nbibler** [comment]
@dijonkitchen It does use Semantic Versioning, that's correct. The `0` major indicates that a library has an unstable / in flux / under development API or interface that is likely to change. A 1.0+ version indicates a stable public interface which the developer is willing to support throughout a major version cycle.

That said, the public API / interface to the library and even functionality of it hasn't changed in ... about two years? Seems stable enough to me for a 1.0 release. 😄

**Comment by justinforce** [comment]
@dijonkitchen I totally thought that you were right, but the link you provided shows that @nbibler is right.

<http://semver.org/#spec-item-4>:

> 4. Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.
> 5. Version 1.0.0 defines the public API. The way in which the version number is incremented after this release is dependent on this public API and how it changes.
