### ISSUE TITLE
Not working on Cedar Stack

### ISSUE THREAD

**Issue by calvinl** [tylerhunt/rack-canonical-host#35]
I've got `CANONICAL_HOST` set up as a config/env var in my application as `www.hostname.com`.

This is my `config.ru`:
```
# This file is used by Rack-based servers to start the application.
require ::File.expand_path('../config/environment', __FILE__)
use Rack::CanonicalHost, ENV['CANONICAL_HOST'] if ENV['CANONICAL_HOST']
run Rails.application
```

Running Rails 4.2.2.

Requests to `hostname.com` don't get redirected to `www.hostname.com`. Am I missing something?

**Comment by tylerhunt** [comment]
I'm not sure that `config/env` is a location Rails will load by default. Is there a gem you're using to load that file for you?

I would check to make sure the environment variable is being set as you expect, because otherwise the syntax looks correct.
