### ISSUE TITLE
ignore path

### ISSUE THREAD

**Issue by azisaka** [tylerhunt/rack-canonical-host#43]
Hi!

I was wondering if you would accept a pull request to make the middleware ignore certain paths.
For example, I have a CDN pointing to my application. And I don't want to force SSL on the CDN, so I need to be able to ignore the /assets/* 

I want to implement it, but first I need to make sure you want it as well :)

**Comment by tylerhunt** [comment]
One way to handle this is to use the block form. For example, if you wanted to avoid redirecting for requests coming from Amazon CloudFront:

``` ruby
use Rack::CanonicalHost, 'secure.example.com' do |env|
  # bypass redirection for CloudFront requests
  if env['HTTP_USER_AGENT'] == 'Amazon CloudFront'
    env['HTTP_HOST']
  end
end
```

If the block returns `nil`, the host value given as the first argument will be used.

**Comment by marckohlbrugge** [comment]
The above approach doesn't seem to work in at least Rails 5.1 since the `env` isn't defined yet.
