### ISSUE TITLE
Passenger behind haproxy

### ISSUE THREAD

**Issue by DSalko** [tylerhunt/rack-canonical-host#46]
Hello

In my setup... haproxy stands before nginx with passenger, so app works on port 7001 internally, and canonical host redirects to https://example.com:7001 instead of https://example.com because of this.

Any way to override port for redirect url?

thanks

**Comment by nbibler** [comment]
It would be surprising to me that rack-canonical-host is redirecting to a different port. I would guess that it's another gem or Rails which is redirecting.

If you're using rack-ssl (which is part of Rails) to `config.force_ssl = true`, it is somewhat more likely that HAProxy is either not sending through the `X-Forwarded-Proto` header or your application is not respecting it. That is causing rack-ssl to think it needs to redirect and putting an incorrect port number on the redirection.
