### ISSUE TITLE
Update Rack dependency to v2.0.0

### ISSUE THREAD

**Issue by nycdavid** [tylerhunt/rack-canonical-host#49]
Is there any value to upgrading the `gemspec` to use `rack` >= 2.0?

**Comment by tylerhunt** [comment]
Not that I'm aware of. As it stands now, it should work with both `~1.0` and `~2.0` to allow people on older apps to continue using it while also supporting Rack 2 (which is a dependency of Rails 5). The support for Rack 2 was added nearly a year ago, and appears to be working just fine judging by the dearth of issues reported.
