### ISSUE TITLE
Exact match on string :if option

### ISSUE THREAD

**Issue by erikdahlstrand** [tylerhunt/rack-canonical-host#53]
Hi,

I was expecting an exact match when using a string on the `if:`option. In a multi-domain environment I want to redirect the APEX domains to the matching www-subdomains. I don't want redirections for any other subdomains like api.* or staging.*

I thought this would be enough:

```
use Rack::CanonicalHost, 'www.mysite1.com', if: 'mysite1.com'
use Rack::CanonicalHost, 'www.mysite2.com', if: 'mysite2.com'
```

The above configuration will also redirect api.mysite1.com and staging.mysite2.com etcetera. I know this can be avoided by using the `ignore:` option. I'm just surprised that `if: 'mysite1.com'` isn't an exact match. 

Maybe I'm supposed to use a regex instead, something like `if: /^mysite1\.com/` ?

**Comment by wvteijlingen** [comment]
I'm running into the same problem. How did you solve this?

**Comment by erikdahlstrand** [comment]
@wvteijlingen I ended up adding sites I don't want to redirect to the `ignore:` option.

**Comment by wvteijlingen** [comment]
Hm yeah that works. Too bad this issue is not fixed yet, or even replied to.
